services:
  bot:
    build: .
    environment:
      - INSTANCE_ID=${HOSTNAME:-bot-instance}
      - DATA_DIR=/data
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all      - BOT_MODE=${BOT_MODE:-collect}
    ports:
      - "5900-5950:5900-5950"  # Wider range to accommodate multiple containers
    volumes:
      - ./training_data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute, graphics, display]
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE  # Needed for some debugging tools
    shm_size: 2gb   # Increase shared memory for better X11 performance
