services:  
  coordinator:
    build: .
    command: python3 container_experiments.py --coordinator
    ports:
      - "9999:9999/udp"
    volumes:
      - ./training_data:/data
    networks:
      - bot-network
  bot:
    build: .
    environment:
      - INSTANCE_ID=${HOSTNAME:-bot-instance}
      - DATA_DIR=/data
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - BOT_MODE=${BOT_MODE:-vnc}
      - COORDINATOR_HOST=coordinator
    ports:
      - "5900-6000"
    depends_on:
      - coordinator
    networks:
      - bot-network
    volumes:
      - ./training_data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /c/Users/pearu/Documents/GitHub/yapb-ML/BotsProjects/yapb/ai_training/autoexec/autoexec.cfg:/opt/assaultcube/config/autoexec.cfg:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute, graphics, display]
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    shm_size: 2gb

networks:
  bot-network:
    driver: bridge
