services:
  bot:
    build: .
    environment:
      - INSTANCE_ID=${HOSTNAME:-bot-instance}
      - DATA_DIR=/data
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - BOT_MODE=${BOT_MODE:-collect}
    ports:
      - "5900:5900"  # Map VNC port directly
    volumes:
      - ./training_data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute, graphics, display]
    stdin_open: true
    tty: true
