//
// YaPB, based on PODBot by Markus Klinge ("CountFloyd").
// Copyright © YaPB Project Developers <yapb@jeefo.net>.
//
// SPDX-License-Identifier: MIT
//

#pragma once

// generated by meson/cmake build system
#ifndef MODULE_BUILD_HASH
#  define MODULE_COMMIT_COUNT "1185"
#  define MODULE_COMMIT_HASH "9300e0854"
#  define MODULE_AUTHOR "pearuarmasj@gmail.com"
#  define MODULE_MACHINE "AUTISM"
#  define MODULE_COMPILER "MSVC 19.44.35209.0"
#  define MODULE_VERSION "4.5"
#  define MODULE_VERSION_FILE 4,5,1185
#  define MODULE_BUILD_ID "1185:9300e0854"
#endif
